<?php

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Talente
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

$talent_gruppe = array();
$talent_gruppe['kampf'] = 'Kampftechniken';
$talent_gruppe['koerper'] = 'Körperliche Talente';
$talent_gruppe['gesellschaft'] = 'Gesellschaftliche Talente';
$talent_gruppe['natur'] = 'Natur-talente';
$talent_gruppe['meta'] = 'Meta-talente';
$talent_gruppe['wissen'] = 'Wissenstalente';
$talent_gruppe['sprache'] = 'Sprachen';
$talent_gruppe['schrift'] = 'Schriften';
$talent_gruppe['handwerk'] = 'Handwerkliche Talente';
$talent_gruppe['gabe'] = 'Gaben';
$talent_gruppe['ritualkenntnis'] = 'Ritualkenntnis';
$talent_gruppe['liturgiekenntnis'] = 'Liturgiekenntnis';
$talent_gruppe['ritualfertigkeit'] = 'Ritualfertigkeit';
$talent_gruppe['schwarzegabe'] = 'Schwarze Gabe';

$talent_data = array();
$talent_data['Anderthalbhänder']         = array( 'gruppe' => 'kampf', 'category' => 'E', 'basis' => false, 'probe' => 'GE/GE/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Nahkampf',  'eBE' => '$be-2', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Armbrust']                 = array( 'gruppe' => 'kampf', 'category' => 'C', 'basis' => false, 'probe' => 'GE/FF/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Fernkampf', 'eBE' => '$be-5', 'typ' => 'fernkampf', 'at_only' => true );
$talent_data['Belagerungswaffen']        = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => false, 'probe' => 'GE/FF/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Fernkampf', 'eBE' => '0',     'typ' => 'fernkampf', 'at_only' => true );
$talent_data['Blasrohr']                 = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => false, 'probe' => 'GE/FF/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Fernkampf', 'eBE' => '$be-5', 'typ' => 'fernkampf', 'at_only' => true );
$talent_data['Bogen']                    = array( 'gruppe' => 'kampf', 'category' => 'E', 'basis' => false, 'probe' => 'GE/FF/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Fernkampf', 'eBE' => '$be-3', 'typ' => 'fernkampf', 'at_only' => true );
$talent_data['Diskus']                   = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => false, 'probe' => 'GE/FF/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Fernkampf', 'eBE' => '$be-2', 'typ' => 'fernkampf', 'at_only' => true );
$talent_data['Dolche']                   = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => true,  'probe' => 'GE/GE/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Nahkampf',  'eBE' => '$be-1', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Fechtwaffen']              = array( 'gruppe' => 'kampf', 'category' => 'E', 'basis' => false, 'probe' => 'GE/GE/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Nahkampf',  'eBE' => '$be-1', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Hiebwaffen']               = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => true,  'probe' => 'GE/GE/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Nahkampf',  'eBE' => '$be-4', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Infanteriewaffen']         = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => false, 'probe' => 'GE/GE/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Nahkampf',  'eBE' => '$be-3', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Kettenstäbe']              = array( 'gruppe' => 'kampf', 'category' => 'E', 'basis' => false, 'probe' => 'GE/GE/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Nahkampf',  'eBE' => '$be-1', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Kettenwaffen']             = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => false, 'probe' => 'GE/GE/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Nahkampf',  'eBE' => '$be-3', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Lanzenreiten']             = array( 'gruppe' => 'kampf', 'category' => 'E', 'basis' => false, 'probe' => 'GE/GE/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Nahkampf',  'eBE' => '0',     'typ' => 'nahkampf',  'at_only' => true );
$talent_data['Peitsche']                 = array( 'gruppe' => 'kampf', 'category' => 'E', 'basis' => false, 'probe' => 'GE/GE/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Nahkampf',  'eBE' => '$be-1', 'typ' => 'nahkampf',  'at_only' => true );
$talent_data['Raufen']                   = array( 'gruppe' => 'kampf', 'category' => 'C', 'basis' => true,  'probe' => 'GE/GE/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Nahkampf',  'eBE' => '$be',   'typ' => 'waffenlos', 'at_only' => false );
$talent_data['Ringen']                   = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => true,  'probe' => 'GE/GE/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Nahkampf',  'eBE' => '$be',   'typ' => 'waffenlos', 'at_only' => false );
$talent_data['Säbel']                    = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => true,  'probe' => 'GE/GE/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Nahkampf',  'eBE' => '$be-2', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Schleuder']                = array( 'gruppe' => 'kampf', 'category' => 'E', 'basis' => false, 'probe' => 'GE/FF/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Fernkampf', 'eBE' => '$be-2', 'typ' => 'fernkampf', 'at_only' => true );
$talent_data['Schwerter']                = array( 'gruppe' => 'kampf', 'category' => 'E', 'basis' => false, 'probe' => 'GE/GE/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Nahkampf',  'eBE' => '$be-2', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Speere']                   = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => false, 'probe' => 'GE/GE/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Nahkampf',  'eBE' => '$be-3', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Stäbe']                    = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => false, 'probe' => 'GE/GE/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Nahkampf',  'eBE' => '$be-2', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Wurfbeile']                = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => false, 'probe' => 'GE/FF/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Fernkampf', 'eBE' => '$be-2', 'typ' => 'fernkampf', 'at_only' => true );
$talent_data['Wurfmesser']               = array( 'gruppe' => 'kampf', 'category' => 'C', 'basis' => true,  'probe' => 'GE/FF/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Fernkampf', 'eBE' => '$be-3', 'typ' => 'fernkampf', 'at_only' => true );
$talent_data['Wurfspeere']               = array( 'gruppe' => 'kampf', 'category' => 'C', 'basis' => false, 'probe' => 'GE/FF/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Fernkampf', 'eBE' => '$be-2', 'typ' => 'fernkampf', 'at_only' => true );
$talent_data['Zweihandflegel']           = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => false, 'probe' => 'GE/GE/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Nahkampf',  'eBE' => '$be-3', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Zweihandhiebwaffen']       = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => false, 'probe' => 'GE/GE/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Nahkampf',  'eBE' => '$be-3', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Zweihandschwerter/-säbel'] = array( 'gruppe' => 'kampf', 'category' => 'E', 'basis' => false, 'probe' => 'GE/GE/KK', 'match' => 'talentgruppe=Kampf;talentgruppe=Nahkampf',  'eBE' => '$be-2', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Akrobatik']                = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => false, 'probe' => 'MU/GE/KK', 'match' => 'talentgruppe=Körperlich', 'eBE' => '$be*2' );
$talent_data['Athletik']                 = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => true,  'probe' => 'GE/KO/KK', 'match' => 'talentgruppe=Körperlich', 'eBE' => '$be*2' );
$talent_data['Fliegen']                  = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => false, 'probe' => 'MU/IN/GE', 'match' => 'talentgruppe=Körperlich', 'eBE' => '$be' );
$talent_data['Gaukeleien']               = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => false, 'probe' => 'MU/CH/FF', 'match' => 'talentgruppe=Körperlich', 'eBE' => '$be*2' );
$talent_data['Immanspiel']               = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => false, 'probe' => 'IN/GE/KK', 'match' => 'talentgruppe=Körperlich', 'eBE' => '0' );
$talent_data['Klettern']                 = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => true,  'probe' => 'MU/GE/KK', 'match' => 'talentgruppe=Körperlich', 'eBE' => '$be*2' );
$talent_data['Körperbeherrschung']       = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => true,  'probe' => 'MU/IN/GE', 'match' => 'talentgruppe=Körperlich', 'eBE' => '$be*2' );
$talent_data['Reiten']                   = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => false, 'probe' => 'CH/GE/KK', 'match' => 'talentgruppe=Körperlich', 'eBE' => '$be-2' );
$talent_data['Schleichen']               = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => true,  'probe' => 'MU/IN/GE', 'match' => 'talentgruppe=Körperlich', 'eBE' => '$be' );
$talent_data['Schwimmen']                = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => true,  'probe' => 'GE/KO/KK', 'match' => 'talentgruppe=Körperlich', 'eBE' => '$be*2' );
$talent_data['Selbstbeherrschung']       = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => true,  'probe' => 'MU/KO/KK', 'match' => 'talentgruppe=Körperlich', 'eBE' => '0' );
$talent_data['Sich verstecken']          = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => true,  'probe' => 'MU/IN/GE', 'match' => 'talentgruppe=Körperlich', 'eBE' => '$be-2' );
$talent_data['Singen']                   = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => true,  'probe' => 'IN/CH/CH', 'match' => 'talentgruppe=Körperlich', 'eBE' => '$be-3' );
$talent_data['Sinnenschärfe']            = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => true,  'probe' => 'KL/IN/IN', 'match' => 'talentgruppe=Körperlich', 'eBE' => '0' );
$talent_data['Skifahren']                = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => false, 'probe' => 'GE/GE/KO', 'match' => 'talentgruppe=Körperlich', 'eBE' => '$be-2' );
$talent_data['Stimmen imitieren']        = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => false, 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Körperlich', 'eBE' => '$be-4' );
$talent_data['Tanzen']                   = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => true,  'probe' => 'CH/GE/GE', 'match' => 'talentgruppe=Körperlich', 'eBE' => '$be*2' );
$talent_data['Taschendiebstahl']         = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => false, 'probe' => 'MU/IN/FF', 'match' => 'talentgruppe=Körperlich', 'eBE' => '$be*2' );
$talent_data['Zechen']                   = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => true,  'probe' => 'IN/KO/KK', 'match' => 'talentgruppe=Körperlich', 'eBE' => '0' );
$talent_data['Betören']                  = array( 'gruppe' => 'gesellschaft', 'category' => 'B', 'basis' => false, 'probe' => 'IN/CH/CH', 'match' => 'talentgruppe=Gesellschaft' );
$talent_data['Etikette']                 = array( 'gruppe' => 'gesellschaft', 'category' => 'B', 'basis' => false, 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Gesellschaft' );
$talent_data['Gassenwissen']             = array( 'gruppe' => 'gesellschaft', 'category' => 'B', 'basis' => false, 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Gesellschaft' );
$talent_data['Lehren']                   = array( 'gruppe' => 'gesellschaft', 'category' => 'B', 'basis' => false, 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Gesellschaft' );
$talent_data['Menschenkenntnis']         = array( 'gruppe' => 'gesellschaft', 'category' => 'B', 'basis' => true,  'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Gesellschaft' );
$talent_data['Schauspielerei']           = array( 'gruppe' => 'gesellschaft', 'category' => 'B', 'basis' => false, 'probe' => 'MU/KL/CH', 'match' => 'talentgruppe=Gesellschaft' );
$talent_data['Schriftlicher Ausdruck']   = array( 'gruppe' => 'gesellschaft', 'category' => 'B', 'basis' => false, 'probe' => 'KL/IN/IN', 'match' => 'talentgruppe=Gesellschaft' );
$talent_data['Sich verkleiden']          = array( 'gruppe' => 'gesellschaft', 'category' => 'B', 'basis' => false, 'probe' => 'MU/CH/GE', 'match' => 'talentgruppe=Gesellschaft' );
$talent_data['Überreden']                = array( 'gruppe' => 'gesellschaft', 'category' => 'B', 'basis' => true,  'probe' => 'MU/IN/CH', 'match' => 'talentgruppe=Gesellschaft' );
$talent_data['Überzeugen']               = array( 'gruppe' => 'gesellschaft', 'category' => 'B', 'basis' => false, 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Gesellschaft' );
$talent_data['Fährtensuchen']            = array( 'gruppe' => 'natur', 'category' => 'B', 'basis' => true,  'probe' => 'KL/IN/KO', 'match' => 'talentgruppe=Natur' );
$talent_data['Fallen stellen']           = array( 'gruppe' => 'natur', 'category' => 'B', 'basis' => false, 'probe' => 'KL/FF/KK', 'match' => 'talentgruppe=Natur' );
$talent_data['Fesseln/Entfesseln']       = array( 'gruppe' => 'natur', 'category' => 'B', 'basis' => false, 'probe' => 'FF/GE/KK', 'match' => 'talentgruppe=Natur' );
$talent_data['Fischen/Angeln']           = array( 'gruppe' => 'natur', 'category' => 'B', 'basis' => false, 'probe' => 'IN/FF/KK', 'match' => 'talentgruppe=Natur' );
$talent_data['Orientierung']             = array( 'gruppe' => 'natur', 'category' => 'B', 'basis' => true,  'probe' => 'KL/IN/IN', 'match' => 'talentgruppe=Natur' );
$talent_data['Wettervorhersage']         = array( 'gruppe' => 'natur', 'category' => 'B', 'basis' => false, 'probe' => 'KL/IN/IN', 'match' => 'talentgruppe=Natur' );
$talent_data['Wildnisleben']             = array( 'gruppe' => 'natur', 'category' => 'B', 'basis' => true,  'probe' => 'IN/GE/KO', 'match' => 'talentgruppe=Natur' );
$talent_data['Jagd: Ansitzjagd']         = array( 'gruppe' => 'meta',  'category' => NULL, 'basis' => true,  'probe' => 'MU/IN/GE', 'factor' => 1/5, 'base' => 'Wildnisleben+Tierkunde+Fährtensuchen+Sich verstecken+Bogen' );
$talent_data['Jagd: Pirschjagd']         = array( 'gruppe' => 'meta',  'category' => NULL, 'basis' => true,  'probe' => 'MU/IN/GE', 'factor' => 1/5, 'base' => 'Wildnisleben+Tierkunde+Fährtensuchen+Schleichen+Bogen' );
$talent_data['Kräuter Suchen']           = array( 'gruppe' => 'meta',  'category' => NULL, 'basis' => true,  'probe' => 'MU/IN/FF', 'factor' => 1/3, 'base' => 'Wildnisleben+Sinnenschärfe+Pflanzenkunde' );
$talent_data['Nahrung Sammeln']          = array( 'gruppe' => 'meta',  'category' => NULL, 'basis' => true,  'probe' => 'MU/IN/FF', 'factor' => 1/3, 'base' => 'Wildnisleben+Sinnenschärfe+Pflanzenkunde' );
$talent_data['Wache Halten']             = array( 'gruppe' => 'meta',  'category' => NULL, 'basis' => true,  'probe' => 'MU/IN/KO', 'factor' => 1/3, 'base' => 'Selbstbeherrschung+Sinnenschärfe+Sinnenschärfe' );
$talent_data['Anatomie']                 = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false, 'probe' => 'MU/KL/FF', 'match' => 'talentgruppe=Wissen' );
$talent_data['Baukunst']                 = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false, 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Wissen' );
$talent_data['Brett-/Kartenspiel']       = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false, 'probe' => 'KL/KL/IN', 'match' => 'talentgruppe=Wissen' );
$talent_data['Deuten der Zeichen']       = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false, 'probe' => 'KL/IN/FF', 'match' => 'talentgruppe=Wissen' );
$talent_data['Geografie']                = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false, 'probe' => 'KL/KL/IN', 'match' => 'talentgruppe=Wissen' );
$talent_data['Geschichtswissen']         = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false, 'probe' => 'KL/KL/IN', 'match' => 'talentgruppe=Wissen' );
$talent_data['Gesteinskunde']            = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false, 'probe' => 'KL/IN/FF', 'match' => 'talentgruppe=Wissen' );
$talent_data['Götter und Kulte']         = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => true,  'probe' => 'KL/KL/IN', 'match' => 'talentgruppe=Wissen' );
$talent_data['Heraldik']                 = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false, 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Wissen' );
$talent_data['Hüttenkunde']              = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false, 'probe' => 'KL/IN/KO', 'match' => 'talentgruppe=Wissen' );
$talent_data['Kriegskunst']              = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false, 'probe' => 'MU/KL/CH', 'match' => 'talentgruppe=Wissen' );
$talent_data['Kryptographie']            = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false, 'probe' => 'KL/KL/IN', 'match' => 'talentgruppe=Wissen' );
$talent_data['Magiekunde']               = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false, 'probe' => 'KL/KL/IN', 'match' => 'talentgruppe=Wissen' );
$talent_data['Mechanik']                 = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false, 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Wissen' );
$talent_data['Pflanzenkunde']            = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false, 'probe' => 'KL/IN/FF', 'match' => 'talentgruppe=Wissen' );
$talent_data['Philosophie']              = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false, 'probe' => 'KL/KL/IN', 'match' => 'talentgruppe=Wissen' );
$talent_data['Rechnen']                  = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => true,  'probe' => 'KL/KL/IN', 'match' => 'talentgruppe=Wissen' );
$talent_data['Rechtskunde']              = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false, 'probe' => 'KL/KL/IN', 'match' => 'talentgruppe=Wissen' );
$talent_data['Sagen und Legenden']       = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => true,  'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Wissen' );
$talent_data['Schätzen']                 = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false, 'probe' => 'KL/IN/IN', 'match' => 'talentgruppe=Wissen' );
$talent_data['Sprachenkunde']            = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false, 'probe' => 'KL/KL/IN', 'match' => 'talentgruppe=Wissen' );
$talent_data['Staatskunst']              = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false, 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Wissen' );
$talent_data['Sternkunde']               = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false, 'probe' => 'KL/KL/IN', 'match' => 'talentgruppe=Wissen' );
$talent_data['Tierkunde']                = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false, 'probe' => 'MU/KL/IN', 'match' => 'talentgruppe=Wissen' );
$talent_data['Sprachen kennen Alaani']                 = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 21, 'family' => 'Tulamidya' );
$talent_data['Sprachen kennen Alt-Imperial/Aureliani'] = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 21, 'family' => 'Garethi' );
$talent_data['Sprachen kennen Altes Kemi']             = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 18, 'family' => 'Tulamidya' );
$talent_data['Sprachen kennen Angram']                 = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 21, 'family' => 'Rogolan' );
$talent_data['Sprachen kennen Asdharia']               = array( 'gruppe' => 'sprache', 'category' => 'C', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 24, 'family' => 'Isdira' );
$talent_data['Sprachen kennen Atak']                   = array( 'gruppe' => 'sprache', 'category' => 'A', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 12 );
$talent_data['Sprachen kennen Bosparano']              = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 21, 'family' => 'Garethi' );
$talent_data['Sprachen kennen Drachisch']              = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 21 );
$talent_data['Sprachen kennen Ferkina']                = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 16, 'family' => 'Tulamidya' );
$talent_data['Sprachen kennen Füchsisch']              = array( 'gruppe' => 'sprache', 'category' => 'A', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 12 );
$talent_data['Sprachen kennen Garethi']                = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 18, 'family' => 'Garethi;Thorwalsch' );
$talent_data['Sprachen kennen Goblinisch']             = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 12, 'family' => 'Goblinisch' );
$talent_data['Sprachen kennen Grolmisch']              = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 17, 'family' => 'Grolmisch' );
$talent_data['Sprachen kennen Hjaldingsch']            = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 18, 'family' => 'Thorwalsch' );
$talent_data['Sprachen kennen Isdira']                 = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 21, 'family' => 'Isdira' );
$talent_data['Sprachen kennen Koboldisch']             = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 15, 'family' => 'Koboldisch' );
$talent_data['Sprachen kennen Mahrisch']               = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 20, 'family' => 'Mahrisch' );
$talent_data['Sprachen kennen Mohisch']                = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 15, 'family' => 'Mohisch' );
$talent_data['Sprachen kennen Molochisch']             = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 17 );
$talent_data['Sprachen kennen Neckergesang']           = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 24 );
$talent_data['Sprachen kennen Nujuka']                 = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 15, 'family' => 'Nujuka' );
$talent_data['Sprachen kennen Oloarkh']                = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 10, 'family' => 'Oloarkh' );
$talent_data['Sprachen kennen Ologhaijan']             = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 15, 'family' => 'Oloarkh' );
$talent_data['Sprachen kennen Rabensprache']           = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 15, 'family' => 'Tulamidya' );
$talent_data['Sprachen kennen Rissoal']                = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 20 );
$talent_data['Sprachen kennen Rogolan']                = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 21, 'family' => 'Rogolan' );
$talent_data['Sprachen kennen Rssahh']                 = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 18, 'family' => 'Rssahh' );
$talent_data['Sprachen kennen Ruuz']                   = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 18, 'family' => 'Tulamidya' );
$talent_data['Sprachen kennen Sprache der Blumen']     = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 18 );
$talent_data['Sprachen kennen Thorwalsch']             = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 18, 'family' => 'Thorwalsch;Garethi' );
$talent_data['Sprachen kennen Trollisch']              = array( 'gruppe' => 'sprache', 'category' => 'A', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 15, 'family' => 'Trollisch' );
$talent_data['Sprachen kennen Tulamidya']              = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 18, 'family' => 'Tulamidya' );
$talent_data['Sprachen kennen Urtulamidya']            = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 21, 'family' => 'Tulamidya' );
$talent_data['Sprachen kennen Z\'Lit']                 = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 17 );
$talent_data['Sprachen kennen Zelemja']                = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 18, 'family' => 'Tulamidya' );
$talent_data['Sprachen kennen Zhayad']                 = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 15, 'family' => 'Zhayad' );
$talent_data['Sprachen kennen Zhulchammaqra']          = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 15, 'family' => 'Tulamidya' );
$talent_data['Sprachen kennen Zyklopäisch']            = array( 'gruppe' => 'sprache', 'category' => 'B', 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 18, 'family' => 'Garethi' );
$talent_data['Lesen/Schreiben (Alt-)Imperiale Zeichen']      = array( 'gruppe' => 'schrift', 'category' => 'B', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 12, 'family' => 'Garethi' );
$talent_data['Lesen/Schreiben Imperiale Zeichen']            = array( 'gruppe' => 'schrift', 'category' => 'B', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 12, 'family' => 'Garethi' );
$talent_data['Lesen/Schreiben Altes Alaani']                 = array( 'gruppe' => 'schrift', 'category' => 'B', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 18, 'family' => 'Tulamidya' );
$talent_data['Lesen/Schreiben Altes Amulashtra']             = array( 'gruppe' => 'schrift', 'category' => 'B', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 17, 'family' => 'Tulamidya' );
$talent_data['Lesen/Schreiben Altes Kemi']                   = array( 'gruppe' => 'schrift', 'category' => 'B', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 21, 'family' => 'Tulamidya' );
$talent_data['Lesen/Schreiben Amulashtra']                   = array( 'gruppe' => 'schrift', 'category' => 'B', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 11, 'family' => 'Tulamidya' );
$talent_data['Lesen/Schreiben Angram']                       = array( 'gruppe' => 'schrift', 'category' => 'B', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 21, 'family' => 'Rogolan' );
$talent_data['Lesen/Schreiben Arkanil']                      = array( 'gruppe' => 'schrift', 'category' => 'D', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 24 );
$talent_data['Lesen/Schreiben Chrmk']                        = array( 'gruppe' => 'schrift', 'category' => 'B', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 18, 'family' => 'Rssahh' );
$talent_data['Lesen/Schreiben Chuchas']                      = array( 'gruppe' => 'schrift', 'category' => 'C', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 24, 'family' => 'Rssahh' );
$talent_data['Lesen/Schreiben Drakhard-Zinken']              = array( 'gruppe' => 'schrift', 'category' => 'B', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 9 );
$talent_data['Lesen/Schreiben Drakned-Glyphen']              = array( 'gruppe' => 'schrift', 'category' => 'C', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 15 );
$talent_data['Lesen/Schreiben Geheiligte Glyphen von Unau']  = array( 'gruppe' => 'schrift', 'category' => 'B', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 13, 'family' => 'Tulamidya' );
$talent_data['Lesen/Schreiben Gimaril-Glyphen']              = array( 'gruppe' => 'schrift', 'category' => 'C', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 10 );
$talent_data['Lesen/Schreiben Gjalskisch']                   = array( 'gruppe' => 'schrift', 'category' => 'B', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 14, 'family' => 'Thorwalsch' );
$talent_data['Lesen/Schreiben Hjaldingsche Runen']           = array( 'gruppe' => 'schrift', 'category' => 'B', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 16, 'family' => 'Thorwalsch' );
$talent_data['Lesen/Schreiben Isdira/Asdharia']              = array( 'gruppe' => 'schrift', 'category' => 'B', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 18, 'family' => 'Isdira' );
$talent_data['Lesen/Schreiben Kusliker Zeichen']             = array( 'gruppe' => 'schrift', 'category' => 'B', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 10, 'family' => 'Garethi' );
$talent_data['Lesen/Schreiben Mahrische Glyphen']            = array( 'gruppe' => 'schrift', 'category' => 'C', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 15, 'family' => 'Mahrisch' );
$talent_data['Lesen/Schreiben Nanduria']                     = array( 'gruppe' => 'schrift', 'category' => 'B', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 10 );
$talent_data['Lesen/Schreiben Rogolan']                      = array( 'gruppe' => 'schrift', 'category' => 'B', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 11, 'family' => 'Rogolan' );
$talent_data['Lesen/Schreiben Trollische Raumbilderschrift'] = array( 'gruppe' => 'schrift', 'category' => 'D', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 24, 'family' => 'Trollisch' );
$talent_data['Lesen/Schreiben Tulamidya']                    = array( 'gruppe' => 'schrift', 'category' => 'B', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 14, 'family' => 'Tulamidya' );
$talent_data['Lesen/Schreiben Urtulamidya']                  = array( 'gruppe' => 'schrift', 'category' => 'B', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 16, 'family' => 'Tulamidya' );
$talent_data['Lesen/Schreiben Zhayad']                       = array( 'gruppe' => 'schrift', 'category' => 'B', 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Sprachen und Schriften', 'komplexity' => 18, 'family' => 'Zhayad' );
$talent_data['Abrichten']               = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'MU/IN/CH', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Ackerbau']                = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'IN/FF/KO', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Alchimie']                = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'MU/KL/FF', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Bergbau']                 = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'IN/KO/KK', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Bogenbau']                = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'KL/IN/FF', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Boote fahren']            = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'GE/KO/KK', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Brauer']                  = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'KL/FF/KK', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Drucker']                 = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'KL/FF/KK', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Fahrzeug lenken']         = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'IN/CH/FF', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Falschspiel']             = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'MU/CH/FF', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Feinmechanik']            = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'KL/FF/FF', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Feuersteinbearbeitung']   = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'KL/FF/FF', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Fleischer']               = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'KL/FF/KK', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Gerber/Kürschner']        = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'KL/FF/KO', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Glaskunst']               = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'FF/FF/KO', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Grobschmied']             = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'FF/KO/KK', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Handel']                  = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'KL/IN/CH', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Hauswirtschaft']          = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'IN/CH/FF', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Heilkunde: Gift']         = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'MU/KL/IN', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Heilkunde: Krankheiten']  = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'MU/KL/CH', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Heilkunde: Seele']        = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'IN/CH/CH', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Heilkunde: Wunden']       = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => true,  'probe' => 'KL/CH/FF', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Holzbearbeitung']         = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => true,  'probe' => 'KL/FF/KK', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Instrumentenbauer']       = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'KL/IN/FF', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Kartografie']             = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'KL/KL/FF', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Kochen']                  = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => true,  'probe' => 'KL/IN/FF', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Kristallzucht']           = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'KL/IN/FF', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Lederarbeiten']           = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => true,  'probe' => 'KL/FF/FF', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Malen/Zeichnen']          = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => true,  'probe' => 'KL/IN/FF', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Maurer']                  = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'FF/GE/KK', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Metallguss']              = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'KL/FF/KK', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Musizieren']              = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'IN/CH/FF', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Schlösser knacken']       = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'IN/FF/FF', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Schnaps brennen']         = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'KL/IN/FF', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Schneidern']              = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => true,  'probe' => 'KL/FF/FF', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Seefahrt']                = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'FF/GE/KK', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Seiler']                  = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'FF/FF/KK', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Steinmetz']               = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'FF/FF/KK', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Steinschneider/Juwelier'] = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'IN/FF/FF', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Stellmacher']             = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'KL/FF/KK', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Stoffe färben']           = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'KL/FF/KK', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Tätowieren']              = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'IN/FF/FF', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Töpfern']                 = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'KL/FF/FF', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Viehzucht']               = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'KL/IN/KK', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Webkunst']                = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'FF/FF/KK', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Winzer']                  = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'KL/FF/KK', 'match' => 'talentgruppe=Handwerk' );
$talent_data['Zimmermann']              = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false, 'probe' => 'KL/FF/KK', 'match' => 'talentgruppe=Handwerk' );

$talent_data['Empathie']                = array( 'gruppe' => 'gabe', 'category' => 'F', 'basis' => false, 'probe' => 'MU/IN/IN' );
$talent_data['Gefahreninstinkt']        = array( 'gruppe' => 'gabe', 'category' => 'F', 'basis' => false, 'probe' => 'KL/IN/IN' );
$talent_data['Geräuschhexerei']         = array( 'gruppe' => 'gabe', 'category' => 'F', 'basis' => false, 'probe' => 'IN/CH/KO' );
$talent_data['Kraftschub']              = array( 'gruppe' => 'gabe', 'category' => 'F', 'basis' => false, 'probe' => 'MU/IN/KO' );
$talent_data['Magiegespür']             = array( 'gruppe' => 'gabe', 'category' => 'F', 'basis' => false, 'probe' => 'MU/IN/IN' );
$talent_data['Prophezeien']             = array( 'gruppe' => 'gabe', 'category' => 'F', 'basis' => false, 'probe' => 'IN/IN/CH' );
$talent_data['Talentschub']             = array( 'gruppe' => 'gabe', 'category' => 'F', 'basis' => false, 'probe' => 'MU/IN/KO' );
$talent_data['Tierempathie']            = array( 'gruppe' => 'gabe', 'category' => 'F', 'basis' => false, 'probe' => 'MU/IN/CH' );
$talent_data['Zwergennase']             = array( 'gruppe' => 'gabe', 'category' => 'F', 'basis' => false, 'probe' => 'IN/IN/FF' );

$talent_data['Liturgiekenntnis']        = array( 'gruppe' => 'liturgiekenntnis', 'category' => 'F', 'basis' => false, 'probe' => 'MU/IN/CH' );

$talent_data['Ritualkenntnis: Alchimist']       = array( 'gruppe' => 'ritualkenntnis', 'category' => 'D', 'basis' => false, 'probe' => '--/--/--' );
$talent_data['Ritualkenntnis: Derwisch']        = array( 'gruppe' => 'ritualkenntnis', 'category' => 'E', 'basis' => false, 'probe' => '--/--/--' );
$talent_data['Ritualkenntnis: Druide']          = array( 'gruppe' => 'ritualkenntnis', 'category' => 'E', 'basis' => false, 'probe' => '--/--/--' );
$talent_data['Ritualkenntnis: Durro-Dûn']       = array( 'gruppe' => 'ritualkenntnis', 'category' => 'E', 'basis' => false, 'probe' => '--/--/--' );
$talent_data['Ritualkenntnis: Geode']           = array( 'gruppe' => 'ritualkenntnis', 'category' => 'E', 'basis' => false, 'probe' => '--/--/--' );
$talent_data['Ritualkenntnis: Gildenmagie']     = array( 'gruppe' => 'ritualkenntnis', 'category' => 'E', 'basis' => false, 'probe' => '--/--/--' );
$talent_data['Ritualkenntnis: Glyphenkunde']    = array( 'gruppe' => 'ritualkenntnis', 'category' => 'E', 'basis' => false, 'probe' => '--/--/--' );
$talent_data['Ritualkenntnis: Hexe']            = array( 'gruppe' => 'ritualkenntnis', 'category' => 'E', 'basis' => false, 'probe' => '--/--/--' );
$talent_data['Ritualkenntnis: Kristallomantie'] = array( 'gruppe' => 'ritualkenntnis', 'category' => 'E', 'basis' => false, 'probe' => '--/--/--' );
$talent_data['Ritualkenntnis: Petromantie']     = array( 'gruppe' => 'ritualkenntnis', 'category' => 'E', 'basis' => false, 'probe' => '--/--/--' );
$talent_data['Ritualkenntnis: Runenzauberei']   = array( 'gruppe' => 'ritualkenntnis', 'category' => 'E', 'basis' => false, 'probe' => '--/--/--' );
$talent_data['Ritualkenntnis: Scharlatan']      = array( 'gruppe' => 'ritualkenntnis', 'category' => 'D', 'basis' => false, 'probe' => '--/--/--' );
$talent_data['Ritualkenntnis: Seher']           = array( 'gruppe' => 'ritualkenntnis', 'category' => 'D', 'basis' => false, 'probe' => '--/--/--' );
$talent_data['Ritualkenntnis: Zaubertänzer']    = array( 'gruppe' => 'ritualkenntnis', 'category' => 'E', 'basis' => false, 'probe' => '--/--/--' );
$talent_data['Ritualkenntnis: Zibilja']         = array( 'gruppe' => 'ritualkenntnis', 'category' => 'E', 'basis' => false, 'probe' => '--/--/--' );

$talent_data['Geister aufnehmen']       = array( 'gruppe' => 'ritualfertigkeit', 'category' => 'E', 'basis' => false, 'probe' => 'MU/IN/KO' );
$talent_data['Geister bannen']          = array( 'gruppe' => 'ritualfertigkeit', 'category' => 'E', 'basis' => false, 'probe' => 'MU/CH/KK' );
$talent_data['Geister binden']          = array( 'gruppe' => 'ritualfertigkeit', 'category' => 'E', 'basis' => false, 'probe' => 'KL/IN/CH' );
$talent_data['Geister rufen']           = array( 'gruppe' => 'ritualfertigkeit', 'category' => 'E', 'basis' => false, 'probe' => 'MU/IN/CH' );

$talent_data['Schwarze Gabe: Alpträume erzeugen']                 = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'KL/IN/CH' );
$talent_data['Schwarze Gabe: Amrychoths Tanz']                    = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'CH/FF/GE' );
$talent_data['Schwarze Gabe: Austrocknen']                        = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'IN/KO/KO' );
$talent_data['Schwarze Gabe: Befehl der Lamijah']                 = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'MU/IN/CH' );
$talent_data['Schwarze Gabe: Begehren überkomme euch!']           = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'CH/CH/IN' );
$talent_data['Schwarze Gabe: Belkelels Ekstase']                  = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'CH/CH/FF' );
$talent_data['Schwarze Gabe: Beutesinn']                          = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'KL/IN/FF' );
$talent_data['Schwarze Gabe: Brünstigkeit erzeugen']              = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'CH/CH/KO' );
$talent_data['Schwarze Gabe: Chimärenerschaffung']                = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'IN/FF/KO' );
$talent_data['Schwarze Gabe: Ertränken']                          = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'MU/CH/KO' );
$talent_data['Schwarze Gabe: Fischgift']                          = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'IN/GE/KO' );
$talent_data['Schwarze Gabe: Geschwindigkeit']                    = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'FF/GE/KO' );
$talent_data['Schwarze Gabe: Gier erzeugen']                      = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'KL/IN/CH' );
$talent_data['Schwarze Gabe: Goldene Hand']                       = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'KL/FF/KO' );
$talent_data['Schwarze Gabe: Hauch der Pestilenz']                = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'IN/FF/KO' );
$talent_data['Schwarze Gabe: Herrschaft über Dschinne']           = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'MU/MU/CH' );
$talent_data['Schwarze Gabe: Herrschaft über Geister']            = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'MU/IN/CH' );
$talent_data['Schwarze Gabe: Katzenruf']                          = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'KL/IN/CH' );
$talent_data['Schwarze Gabe: Kornfäule']                          = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'IN/IN/KO' );
$talent_data['Schwarze Gabe: Krakenhaut']                         = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'MU/IN/GE' );
$talent_data['Schwarze Gabe: Krakenruf']                          = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'MU/CH/IN' );
$talent_data['Schwarze Gabe: Lähmende Furcht']                    = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'MU/CH/KO' );
$talent_data['Schwarze Gabe: Leichengespür']                      = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'MU/IN/FF' );
$talent_data['Schwarze Gabe: Lodernder Blick']                    = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'MU/CH/CH' );
$talent_data['Schwarze Gabe: Macht des Wahnsinns']                = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'KL/KL/CH' );
$talent_data['Schwarze Gabe: Magnum Opus des Erzdämons']          = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'MU/MU/CH' );
$talent_data['Schwarze Gabe: Meister der Form']                   = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'KL/FF/KO' );
$talent_data['Schwarze Gabe: Meister der Maritimen']              = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'MU/CH/CH' );
$talent_data['Schwarze Gabe: Nagrachs Hauch']                     = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'KL/KO/KO' );
$talent_data['Schwarze Gabe: Orkanbö']                            = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'FF/KO/KO' );
$talent_data['Schwarze Gabe: Raub der Lebenskraft']               = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'IN/KO/KO' );
$talent_data['Schwarze Gabe: Schleichen in den Schatten']         = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'CH/FF/GE' );
$talent_data['Schwarze Gabe: Spur des Missetäters']               = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'MU/IN/IN' );
$talent_data['Schwarze Gabe: Todeshauch']                         = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'CH/KK/KO' );
$talent_data['Schwarze Gabe: Trugwelten erschaffen']              = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'KL/IN/CH' );
$talent_data['Schwarze Gabe: Unsichtbarer Jäger']                 = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'IN/CH/KO' );
$talent_data['Schwarze Gabe: Verborgenes Wissen erspüren']        = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'KL/KL/IN' );
$talent_data['Schwarze Gabe: Wahrheitssinn']                      = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'KL/IN/IN' );
$talent_data['Schwarze Gabe: Wundschmerz']                        = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'MU/KO/KK' );
$talent_data['Schwarze Gabe: Zwist und Hader']                    = array( 'gruppe' => 'schwarzegabe', 'category' => 'F', 'basis' => false, 'probe' => 'KL/IN/CH' );

?>