<?php
    
$eigenschaft_gruppe = array();
$eigenschaft_gruppe['eigenschaft'] = 'Eigenschaften';
$eigenschaft_gruppe['energiewert'] = 'Energiewerte';
$eigenschaft_gruppe['basiswert'] = 'Basiswerte';
$eigenschaft_gruppe['sozialstatus'] = 'Sozialstatus';

$eigenschaft_data = array();
$eigenschaft_data['Mut']                     = array( 'gruppe' => 'eigenschaft',  'category' => 'H', 'basis' => true );
$eigenschaft_data['Klugheit']                = array( 'gruppe' => 'eigenschaft',  'category' => 'H', 'basis' => true );
$eigenschaft_data['Intuition']               = array( 'gruppe' => 'eigenschaft',  'category' => 'H', 'basis' => true );
$eigenschaft_data['Charisma']                = array( 'gruppe' => 'eigenschaft',  'category' => 'H', 'basis' => true );
$eigenschaft_data['Fingerfertigkeit']        = array( 'gruppe' => 'eigenschaft',  'category' => 'H', 'basis' => true );
$eigenschaft_data['Gewandtheit']             = array( 'gruppe' => 'eigenschaft',  'category' => 'H', 'basis' => true );
$eigenschaft_data['Konstitution']            = array( 'gruppe' => 'eigenschaft',  'category' => 'H', 'basis' => true );
$eigenschaft_data['Körperkraft']             = array( 'gruppe' => 'eigenschaft',  'category' => 'H', 'basis' => true );
$eigenschaft_data['Magieresistenz']          = array( 'gruppe' => 'energiewert',  'category' => 'H', 'basis' => true,  'factor' => 0.2, 'base' => 'Mut+Klugheit+Konstitution' );
$eigenschaft_data['Lebensenergie']           = array( 'gruppe' => 'energiewert',  'category' => 'H', 'basis' => true,  'factor' => 0.5, 'base' => 'Konstitution+Konstitution+Körperkraft' );
$eigenschaft_data['Ausdauer']                = array( 'gruppe' => 'energiewert',  'category' => 'E', 'basis' => true,  'factor' => 0.5, 'base' => 'Mut+Konstitution+Gewandtheit' );
$eigenschaft_data['Astralenergie']           = array( 'gruppe' => 'energiewert',  'category' => 'G', 'basis' => false, 'factor' => 0.5, 'base' => 'Mut+Intuition+Charisma' );
$eigenschaft_data['Karmaenergie']            = array( 'gruppe' => 'energiewert',  'category' => NULL, 'basis' => false );
$eigenschaft_data['Attacke Basiswert']       = array( 'gruppe' => 'basiswert',    'category' => NULL, 'basis' => true, 'factor' => 0.2, 'base' => 'Mut+Gewandtheit+Körperkraft' );
$eigenschaft_data['Parade Basiswert']        = array( 'gruppe' => 'basiswert',    'category' => NULL, 'basis' => true, 'factor' => 0.2, 'base' => 'Intuition+Gewandtheit+Körperkraft' );
$eigenschaft_data['Fernkampf Basiswert']     = array( 'gruppe' => 'basiswert',    'category' => NULL, 'basis' => true, 'factor' => 0.2, 'base' => 'Intuition+Fingerfertigkeit+Körperkraft' );
$eigenschaft_data['Initiative Basiswert']    = array( 'gruppe' => 'basiswert',    'category' => NULL, 'basis' => true, 'factor' => 0.2, 'base' => 'Mut+Mut+Intuition+Gewandtheit' );
$eigenschaft_data['Sozialstatus']            = array( 'gruppe' => 'sozialstatus', 'category' => NULL, 'basis' => true );


$talent_gruppe = array();
$talent_gruppe['kampf'] = 'Kampftechniken';
$talent_gruppe['koerper'] = 'Körperliche Talente';
$talent_gruppe['gesellschaft'] = 'Gesellschaftliche Talente';
$talent_gruppe['natur'] = 'Natur-talente';
$talent_gruppe['wissen'] = 'Wissenstalente';
$talent_gruppe['sprache'] = 'Sprachen';
$talent_gruppe['schrift'] = 'Schriften';
$talent_gruppe['handwerk'] = 'Handwerkliche Talente';
$talent_gruppe['gabe'] = 'Gaben';

$talent_data = array();
$talent_data['Anderthalbhänder']         = array( 'gruppe' => 'kampf', 'category' => 'E', 'basis' => false, 'eBE' => '$be-2', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Armbrust']                 = array( 'gruppe' => 'kampf', 'category' => 'C', 'basis' => false, 'eBE' => '$be-5', 'typ' => 'fernkampf', 'at_only' => true );
$talent_data['Belagerungswaffen']        = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => false, 'eBE' => '0',     'typ' => 'fernkampf', 'at_only' => true );
$talent_data['Blasrohr']                 = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => false, 'eBE' => '$be-5', 'typ' => 'fernkampf', 'at_only' => true );
$talent_data['Bogen']                    = array( 'gruppe' => 'kampf', 'category' => 'E', 'basis' => false, 'eBE' => '$be-3', 'typ' => 'fernkampf', 'at_only' => true );
$talent_data['Diskus']                   = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => false, 'eBE' => '$be-2', 'typ' => 'fernkampf', 'at_only' => true );
$talent_data['Dolche']                   = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => true,  'eBE' => '$be-1', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Fechtwaffen']              = array( 'gruppe' => 'kampf', 'category' => 'E', 'basis' => false, 'eBE' => '$be-1', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Hiebwaffen']               = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => true,  'eBE' => '$be-4', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Infanteriewaffen']         = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => false, 'eBE' => '$be-3', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Kettenstäbe']              = array( 'gruppe' => 'kampf', 'category' => 'E', 'basis' => false, 'eBE' => '$be-1', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Kettenwaffen']             = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => false, 'eBE' => '$be-3', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Lanzenreiten']             = array( 'gruppe' => 'kampf', 'category' => 'E', 'basis' => false, 'eBE' => '0',     'typ' => 'nahkampf',  'at_only' => true );
$talent_data['Peitsche']                 = array( 'gruppe' => 'kampf', 'category' => 'E', 'basis' => false, 'eBE' => '$be-1', 'typ' => 'nahkampf',  'at_only' => true );
$talent_data['Raufen']                   = array( 'gruppe' => 'kampf', 'category' => 'C', 'basis' => true,  'eBE' => '$be',   'typ' => 'waffenlos', 'at_only' => false );
$talent_data['Ringen']                   = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => true,  'eBE' => '$be',   'typ' => 'waffenlos', 'at_only' => false );
$talent_data['Säbel']                    = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => true,  'eBE' => '$be-2', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Schleuder']                = array( 'gruppe' => 'kampf', 'category' => 'E', 'basis' => false, 'eBE' => '$be-2', 'typ' => 'fernkampf', 'at_only' => true );
$talent_data['Schwerter']                = array( 'gruppe' => 'kampf', 'category' => 'E', 'basis' => false, 'eBE' => '$be-2', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Speere']                   = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => false, 'eBE' => '$be-3', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Stäbe']                    = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => false, 'eBE' => '$be-2', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Wurfbeile']                = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => false, 'eBE' => '$be-2', 'typ' => 'fernkampf', 'at_only' => true );
$talent_data['Wurfmesser']               = array( 'gruppe' => 'kampf', 'category' => 'C', 'basis' => true,  'eBE' => '$be-3', 'typ' => 'fernkampf', 'at_only' => true );
$talent_data['Wurfspeere']               = array( 'gruppe' => 'kampf', 'category' => 'C', 'basis' => false, 'eBE' => '$be-2', 'typ' => 'fernkampf', 'at_only' => true );
$talent_data['Zweihandflegel']           = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => false, 'eBE' => '$be-3', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Zweihandhiebwaffen']       = array( 'gruppe' => 'kampf', 'category' => 'D', 'basis' => false, 'eBE' => '$be-3', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Zweihandschwerter/-säbel'] = array( 'gruppe' => 'kampf', 'category' => 'E', 'basis' => false, 'eBE' => '$be-2', 'typ' => 'nahkampf',  'at_only' => false );
$talent_data['Akrobatik']                = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => false, 'eBE' => '$be*2' );
$talent_data['Athletik']                 = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => true,  'eBE' => '$be*2' );
$talent_data['Fliegen']                  = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => false, 'eBE' => '$be' );
$talent_data['Gaukeleien']               = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => false, 'eBE' => '$be*2' );
$talent_data['Immanspiel']               = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => false, 'eBE' => '0' );
$talent_data['Klettern']                 = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => true,  'eBE' => '$be*2' );
$talent_data['Körperbeherrschung']       = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => true,  'eBE' => '$be*2' );
$talent_data['Reiten']                   = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => false, 'eBE' => '$be-2' );
$talent_data['Schleichen']               = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => true,  'eBE' => '$be' );
$talent_data['Schwimmen']                = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => true,  'eBE' => '$be*2' );
$talent_data['Selbstbeherrschung']       = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => true,  'eBE' => '0' );
$talent_data['Sich verstecken']          = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => true,  'eBE' => '$be-2' );
$talent_data['Singen']                   = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => true,  'eBE' => '$be-3' );
$talent_data['Sinnenschärfe']            = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => true,  'eBE' => '0' );
$talent_data['Skifahren']                = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => false, 'eBE' => '$be-2' );
$talent_data['Stimmen imitieren']        = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => false, 'eBE' => '$be-4' );
$talent_data['Tanzen']                   = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => true,  'eBE' => '$be*2' );
$talent_data['Taschendiebstahl']         = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => false, 'eBE' => '$be*2' );
$talent_data['Zechen']                   = array( 'gruppe' => 'koerper', 'category' => 'D', 'basis' => true,  'eBE' => '0' );
$talent_data['Betören']                  = array( 'gruppe' => 'gesellschaft', 'category' => 'B', 'basis' => false );
$talent_data['Etikette']                 = array( 'gruppe' => 'gesellschaft', 'category' => 'B', 'basis' => false );
$talent_data['Gassenwissen']             = array( 'gruppe' => 'gesellschaft', 'category' => 'B', 'basis' => false );
$talent_data['Lehren']                   = array( 'gruppe' => 'gesellschaft', 'category' => 'B', 'basis' => false );
$talent_data['Menschenkenntnis']         = array( 'gruppe' => 'gesellschaft', 'category' => 'B', 'basis' => true );
$talent_data['Schauspielerei']           = array( 'gruppe' => 'gesellschaft', 'category' => 'B', 'basis' => false );
$talent_data['Schriftlicher Ausdruck']   = array( 'gruppe' => 'gesellschaft', 'category' => 'B', 'basis' => false );
$talent_data['Sich verkleiden']          = array( 'gruppe' => 'gesellschaft', 'category' => 'B', 'basis' => false );
$talent_data['Überreden']                = array( 'gruppe' => 'gesellschaft', 'category' => 'B', 'basis' => true );
$talent_data['Überzeugen']               = array( 'gruppe' => 'gesellschaft', 'category' => 'B', 'basis' => false );
$talent_data['Fährtensuchen']            = array( 'gruppe' => 'natur', 'category' => 'B', 'basis' => true );
$talent_data['Fallen stellen']           = array( 'gruppe' => 'natur', 'category' => 'B', 'basis' => false );
$talent_data['Fesseln/Entfesseln']       = array( 'gruppe' => 'natur', 'category' => 'B', 'basis' => false );
$talent_data['Fischen/Angeln']           = array( 'gruppe' => 'natur', 'category' => 'B', 'basis' => false );
$talent_data['Orientierung']             = array( 'gruppe' => 'natur', 'category' => 'B', 'basis' => true );
$talent_data['Wettervorhersage']         = array( 'gruppe' => 'natur', 'category' => 'B', 'basis' => false );
$talent_data['Wildnisleben']             = array( 'gruppe' => 'natur', 'category' => 'B', 'basis' => true );
$talent_data['Anatomie']                 = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false );
$talent_data['Baukunst']                 = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false );
$talent_data['Brett-/Kartenspiel']       = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false );
$talent_data['Deuten der Zeichen']       = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false );
$talent_data['Geografie']                = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false );
$talent_data['Geschichtswissen']         = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false );
$talent_data['Gesteinskunde']            = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false );
$talent_data['Götter und Kulte']         = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => true );
$talent_data['Heraldik']                 = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false );
$talent_data['Hüttenkunde']              = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false );
$talent_data['Kriegskunst']              = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false );
$talent_data['Kryptographie']            = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false );
$talent_data['Magiekunde']               = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false );
$talent_data['Mechanik']                 = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false );
$talent_data['Pflanzenkunde']            = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false );
$talent_data['Philosophie']              = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false );
$talent_data['Rechnen']                  = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => true );
$talent_data['Rechtskunde']              = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false );
$talent_data['Sagen und Legenden']       = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => true );
$talent_data['Schätzen']                 = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false );
$talent_data['Sprachenkunde']            = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false );
$talent_data['Staatskunst']              = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false );
$talent_data['Sternkunde']               = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false );
$talent_data['Tierkunde']                = array( 'gruppe' => 'wissen', 'category' => 'B', 'basis' => false );
$talent_data['Sprachen kennen Alaani']                 = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 21, 'family' => 'Tulamidya' );
$talent_data['Sprachen kennen Alt-Imperial/Aureliani'] = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 21, 'family' => 'Garethi' );
$talent_data['Sprachen kennen Altes Kemi']             = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 18, 'family' => 'Tulamidya' );
$talent_data['Sprachen kennen Angram']                 = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 21, 'family' => 'Rogolan' );
$talent_data['Sprachen kennen Asdharia']               = array( 'gruppe' => 'sprache', 'category' => 'C', 'komplexity' => 24, 'family' => 'Isdira' );
$talent_data['Sprachen kennen Atak']                   = array( 'gruppe' => 'sprache', 'category' => 'A', 'komplexity' => 12 );
$talent_data['Sprachen kennen Bosparano']              = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 21, 'family' => 'Garethi' );
$talent_data['Sprachen kennen Drachisch']              = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 21 );
$talent_data['Sprachen kennen Ferkina']                = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 16, 'family' => 'Tulamidya' );
$talent_data['Sprachen kennen Füchsisch']              = array( 'gruppe' => 'sprache', 'category' => 'A', 'komplexity' => 12 );
$talent_data['Sprachen kennen Garethi']                = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 18, 'family' => 'Garethi;Thorwalsch' );
$talent_data['Sprachen kennen Goblinisch']             = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 12, 'family' => 'Goblinisch' );
$talent_data['Sprachen kennen Grolmisch']              = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 17, 'family' => 'Grolmisch' );
$talent_data['Sprachen kennen Hjaldingsch']            = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 18, 'family' => 'Thorwalsch' );
$talent_data['Sprachen kennen Isdira']                 = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 21, 'family' => 'Isdira' );
$talent_data['Sprachen kennen Koboldisch']             = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 15, 'family' => 'Koboldisch' );
$talent_data['Sprachen kennen Mahrisch']               = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 20, 'family' => 'Mahrisch' );
$talent_data['Sprachen kennen Mohisch']                = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 15, 'family' => 'Mohisch' );
$talent_data['Sprachen kennen Molochisch']             = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 17 );
$talent_data['Sprachen kennen Neckergesang']           = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 24 );
$talent_data['Sprachen kennen Nujuka']                 = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 15, 'family' => 'Nujuka' );
$talent_data['Sprachen kennen Oloarkh']                = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 10, 'family' => 'Oloarkh' );
$talent_data['Sprachen kennen Ologhaijan']             = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 15, 'family' => 'Oloarkh' );
$talent_data['Sprachen kennen Rabensprache']           = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 15, 'family' => 'Tulamidya' );
$talent_data['Sprachen kennen Rissoal']                = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 20 );
$talent_data['Sprachen kennen Rogolan']                = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 21, 'family' => 'Rogolan' );
$talent_data['Sprachen kennen Rssahh']                 = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 18, 'family' => 'Rssahh' );
$talent_data['Sprachen kennen Ruuz']                   = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 18, 'family' => 'Tulamidya' );
$talent_data['Sprachen kennen Thorwalsch']             = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 18, 'family' => 'Thorwalsch;Garethi' );
$talent_data['Sprachen kennen Trollisch']              = array( 'gruppe' => 'sprache', 'category' => 'A', 'komplexity' => 15, 'family' => 'Trollisch' );
$talent_data['Sprachen kennen Tulamidya']              = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 18, 'family' => 'Tulamidya' );
$talent_data['Sprachen kennen Urtulamidya']            = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 21, 'family' => 'Tulamidya' );
$talent_data['Sprachen kennen Z\'Lit']                 = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 17 );
$talent_data['Sprachen kennen Zelemja']                = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 18, 'family' => 'Tulamidya' );
$talent_data['Sprachen kennen Zhayad']                 = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 15, 'family' => 'Zhayad' );
$talent_data['Sprachen kennen Zhulchammaqra']          = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 15, 'family' => 'Tulamidya' );
$talent_data['Sprachen kennen Zyklopäisch']            = array( 'gruppe' => 'sprache', 'category' => 'B', 'komplexity' => 18, 'family' => 'Garethi' );
$talent_data['Lesen/Schreiben (Alt-)Imperiale Zeichen']      = array( 'gruppe' => 'schrift', 'category' => 'B', 'komplexity' => 12, 'family' => 'Garethi' );
$talent_data['Lesen/Schreiben Altes Alaani']                 = array( 'gruppe' => 'schrift', 'category' => 'B', 'komplexity' => 18, 'family' => 'Tulamidya' );
$talent_data['Lesen/Schreiben Altes Amulashtra']             = array( 'gruppe' => 'schrift', 'category' => 'B', 'komplexity' => 17, 'family' => 'Tulamidya' );
$talent_data['Lesen/Schreiben Altes Kemi']                   = array( 'gruppe' => 'schrift', 'category' => 'B', 'komplexity' => 21, 'family' => 'Tulamidya' );
$talent_data['Lesen/Schreiben Amulashtra']                   = array( 'gruppe' => 'schrift', 'category' => 'B', 'komplexity' => 11, 'family' => 'Tulamidya' );
$talent_data['Lesen/Schreiben Angram']                       = array( 'gruppe' => 'schrift', 'category' => 'B', 'komplexity' => 21, 'family' => 'Rogolan' );
$talent_data['Lesen/Schreiben Arkanil']                      = array( 'gruppe' => 'schrift', 'category' => 'D', 'komplexity' => 24 );
$talent_data['Lesen/Schreiben Chrmk']                        = array( 'gruppe' => 'schrift', 'category' => 'B', 'komplexity' => 18, 'family' => 'Rssahh' );
$talent_data['Lesen/Schreiben Chuchas']                      = array( 'gruppe' => 'schrift', 'category' => 'C', 'komplexity' => 24, 'family' => 'Rssahh' );
$talent_data['Lesen/Schreiben Drakhard-Zinken']              = array( 'gruppe' => 'schrift', 'category' => 'B', 'komplexity' => 9 );
$talent_data['Lesen/Schreiben Drakned-Glyphen']              = array( 'gruppe' => 'schrift', 'category' => 'C', 'komplexity' => 15 );
$talent_data['Lesen/Schreiben Geheiligte Glyphen von Unau']  = array( 'gruppe' => 'schrift', 'category' => 'B', 'komplexity' => 13, 'family' => 'Tulamidya' );
$talent_data['Lesen/Schreiben Gimaril-Glyphen']              = array( 'gruppe' => 'schrift', 'category' => 'C', 'komplexity' => 10 );
$talent_data['Lesen/Schreiben Gjalskisch']                   = array( 'gruppe' => 'schrift', 'category' => 'B', 'komplexity' => 14, 'family' => 'Thorwalsch' );
$talent_data['Lesen/Schreiben Hjaldingsche Runen']           = array( 'gruppe' => 'schrift', 'category' => 'B', 'komplexity' => 16, 'family' => 'Thorwalsch' );
$talent_data['Lesen/Schreiben Isdira/Asdharia']              = array( 'gruppe' => 'schrift', 'category' => 'B', 'komplexity' => 18, 'family' => 'Isdira' );
$talent_data['Lesen/Schreiben Kusliker Zeichen']             = array( 'gruppe' => 'schrift', 'category' => 'B', 'komplexity' => 10, 'family' => 'Garethi' );
$talent_data['Lesen/Schreiben Mahrische Glyphen']            = array( 'gruppe' => 'schrift', 'category' => 'C', 'komplexity' => 15, 'family' => 'Mahrisch' );
$talent_data['Lesen/Schreiben Nanduria']                     = array( 'gruppe' => 'schrift', 'category' => 'B', 'komplexity' => 10 );
$talent_data['Lesen/Schreiben Rogolan']                      = array( 'gruppe' => 'schrift', 'category' => 'B', 'komplexity' => 11, 'family' => 'Rogolan' );
$talent_data['Lesen/Schreiben Trollische Raumbilderschrift'] = array( 'gruppe' => 'schrift', 'category' => 'D', 'komplexity' => 24, 'family' => 'Trollisch' );
$talent_data['Lesen/Schreiben Tulamidya']                    = array( 'gruppe' => 'schrift', 'category' => 'B', 'komplexity' => 14, 'family' => 'Tulamidya' );
$talent_data['Lesen/Schreiben Urtulamidya']                  = array( 'gruppe' => 'schrift', 'category' => 'B', 'komplexity' => 16, 'family' => 'Tulamidya' );
$talent_data['Lesen/Schreiben Zhayad']                       = array( 'gruppe' => 'schrift', 'category' => 'B', 'komplexity' => 18, 'family' => 'Zhayad' );
$talent_data['Abrichten']               = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Ackerbau']                = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Alchimie']                = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Bergbau']                 = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Bogenbau']                = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Boote fahren']            = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Brauer']                  = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Drucker']                 = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Fahrzeug lenken']         = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Falschspiel']             = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Feinmechanik']            = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Feuersteinbearbeitung']   = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Fleischer']               = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Gerber/Kürschner']        = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Glaskunst']               = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Grobschmied']             = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Handel']                  = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Hauswirtschaft']          = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Heilkunde: Gift']         = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Heilkunde: Krankheiten']  = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Heilkunde: Seele']        = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Heilkunde: Wunden']       = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => true );
$talent_data['Holzbearbeitung']         = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => true );
$talent_data['Instrumentenbauer']       = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Kartografie']             = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Kochen']                  = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => true );
$talent_data['Kristallzucht']           = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Lederarbeiten']           = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => true );
$talent_data['Malen/Zeichnen']          = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => true );
$talent_data['Maurer']                  = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Metallguss']              = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Musizieren']              = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Schlösser knacken']       = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Schnaps brennen']         = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Schneidern']              = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => true );
$talent_data['Seefahrt']                = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Seiler']                  = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Steinmetz']               = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Steinschneider/Juwelier'] = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Stellmacher']             = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Stoffe färben']           = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Tätowieren']              = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Töpfern']                 = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Viehzucht']               = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Webkunst']                = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Winzer']                  = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );
$talent_data['Zimmermann']              = array( 'gruppe' => 'handwerk', 'category' => 'B', 'basis' => false );


$zauber_gruppe = array();
$zauber_gruppe['zauber'] = 'Zauber';

$zauber_data = array();
$zauber_data['...']              = array( 'gruppe' => 'zauber', 'category' => 'B', 'basis' => false );


$sf_gruppe = array();
$sf_gruppe['kampf']     = 'Kampf-Sonderfertigkeiten';
$sf_gruppe['magisch']   = 'Magische Sonderfertigkeiten';
$sf_gruppe['klerikal']  = 'Klerikale Sonderfertigkeiten';
$sf_gruppe['allgemein'] = 'Allgemeine Sonderfertigkeiten';

$sf_data = array();
$sf_data['Aufmerksamkeit']           = array( 'gruppe' => 'kampf', 'rarity' => 6, 'cost' => 200, 'req' => 'Intuition>11' );
$sf_data['Ausfall']                  = array( 'gruppe' => 'kampf', 'rarity' => 4, 'cost' => 200, 'req' => 'Konstitution>11;SF Aufmerksamkeit' );
$sf_data['Ausweichen I']             = array( 'gruppe' => 'kampf', 'rarity' => 5, 'cost' => 300, 'req' => 'Gewandtheit>9' );
$sf_data['Ausweichen II']            = array( 'gruppe' => 'kampf', 'rarity' => 4, 'cost' => 200, 'req' => 'Gewandtheit>11;SF Ausweichen I' );
$sf_data['Ausweichen III']           = array( 'gruppe' => 'kampf', 'rarity' => 3, 'cost' => 200, 'req' => 'Gewandtheit>14;SF Ausweichen II;SF Kampfreflexe' );
$sf_data['Befreiungsschlag']         = array( 'gruppe' => 'kampf', 'rarity' => 3, 'cost' => 100, 'req' => 'Körperkraft>14;Mut>11;SF Niederwerfen' );
$sf_data['Beidhändiger Kampf I']     = array( 'gruppe' => 'kampf', 'rarity' => 3, 'cost' => 100, 'req' => 'Gewandtheit>11;SF Linkhand' );
$sf_data['Beidhändiger Kampf II']    = array( 'gruppe' => 'kampf', 'rarity' => 2, 'cost' => 400, 'req' => 'Gewandtheit>14;SF Beidhändiger Kampf I' );
$sf_data['Betäubungsschlag']         = array( 'gruppe' => 'kampf', 'rarity' => 3, 'cost' => 200, 'req' => 'SF Wuchtschlag;SF Finte' );
$sf_data['Binden']                   = array( 'gruppe' => 'kampf', 'rarity' => 4, 'cost' => 200, 'req' => 'Intuition>11;Gewandtheit>11;SF Meisterparade' );
$sf_data['Blindkampf']               = array( 'gruppe' => 'kampf', 'rarity' => 1, 'cost' => 200, 'req' => 'Gewandtheit>11;Sinnenschärfe>14;SF Kampfgespür' );
$sf_data['Defensiver Kampfstil']     = array( 'gruppe' => 'kampf', 'rarity' => 4, 'cost' => 100, 'req' => 'Gewandtheit>11;SF Meisterparade' );
$sf_data['Doppelangriff']            = array( 'gruppe' => 'kampf', 'rarity' => 3, 'cost' => 100, 'req' => 'SF Beidhändiger Kampf I' );
$sf_data['Entwaffnen']               = array( 'gruppe' => 'kampf', 'rarity' => 3, 'cost' => 200, 'req' => 'Körperkraft>11;SF Binden' );
$sf_data['Finte']                    = array( 'gruppe' => 'kampf', 'rarity' => 6, 'cost' => 200, 'req' => 'Gewandtheit>11' );
$sf_data['Formation']                = array( 'gruppe' => 'kampf', 'rarity' => 5, 'cost' => 100, 'req' => 'SF Aufmerksamkeit' );
$sf_data['Gegenhalten']              = array( 'gruppe' => 'kampf', 'rarity' => 3, 'cost' => 200, 'req' => 'Mut>14;Gewandtheit>11;SF Meisterparade' );
$sf_data['Gezielter Stich']          = array( 'gruppe' => 'kampf', 'rarity' => 4, 'cost' => 100, 'req' => 'SF Finte' );
$sf_data['Halbschwert']              = array( 'gruppe' => 'kampf', 'rarity' => 5, 'cost' => 150, 'req' => 'SF Aufmerksamkeit' );
$sf_data['Hammerschlag']             = array( 'gruppe' => 'kampf', 'rarity' => 3, 'cost' => 200, 'req' => 'Mut>14;SF Niederwerfen' );
$sf_data['Kampfgespür']              = array( 'gruppe' => 'kampf', 'rarity' => 3, 'cost' => 200, 'req' => 'Intuition>14;SF Aufmerksamkeit;SF Kampfreflexe' );
$sf_data['Kampfreflexe']             = array( 'gruppe' => 'kampf', 'rarity' => 4, 'cost' => 300, 'req' => 'Initiative Basiswert>9' );
$sf_data['Klingensturm']             = array( 'gruppe' => 'kampf', 'rarity' => 3, 'cost' => 100, 'req' => 'Attacke Basiswert>8;SF Kampfreflexe;SF Ausfall' );
$sf_data['Klingentänzer']            = array( 'gruppe' => 'kampf', 'rarity' => 1, 'cost' => 400, 'req' => 'Gewandtheit>14;SF Kampfgespür' );
$sf_data['Klingenwand']              = array( 'gruppe' => 'kampf', 'rarity' => 3, 'cost' => 100, 'req' => 'Parade Basiswert>8;SF Kampfreflexe;SF Defensiver Kampfstil' );
$sf_data['Linkhand']                 = array( 'gruppe' => 'kampf', 'rarity' => 6, 'cost' => 300, 'req' => 'Gewandtheit>9;Körperkraft>9' );
$sf_data['Meisterliches Entwaffnen'] = array( 'gruppe' => 'kampf', 'rarity' => 2, 'cost' => 100, 'req' => 'Gewandtheit>14;SF Entwaffnen' );
$sf_data['Meisterparade']            = array( 'gruppe' => 'kampf', 'rarity' => 5, 'cost' => 200, 'req' => 'Parade Basiswert>7' );
$sf_data['Niederwerfen']             = array( 'gruppe' => 'kampf', 'rarity' => 4, 'cost' => 100, 'req' => 'SF Wuchtschlag' );
$sf_data['Parierwaffen I']           = array( 'gruppe' => 'kampf', 'rarity' => 4, 'cost' => 200, 'req' => 'Gewandtheit>11;SF Linkhand' );
$sf_data['Parierwaffen II']          = array( 'gruppe' => 'kampf', 'rarity' => 3, 'cost' => 200, 'req' => 'Gewandtheit>14;SF Parierwaffen I' );
$sf_data['Rüstungsgewöhnung I']      = array( 'gruppe' => 'kampf', 'rarity' => 6, 'cost' => 150, 'req' => 'Körperkraft>9' );
$sf_data['Rüstungsgewöhnung II']     = array( 'gruppe' => 'kampf', 'rarity' => 4, 'cost' => 300, 'req' => 'Körperkraft>11;SF Rüstungsgewöhnung I' );
$sf_data['Rüstungsgewöhnung III']    = array( 'gruppe' => 'kampf', 'rarity' => 2, 'cost' => 450, 'req' => 'Körperkraft>14;SF Rüstungsgewöhnung II' );
$sf_data['Schildkampf I']            = array( 'gruppe' => 'kampf', 'rarity' => 6, 'cost' => 200, 'req' => 'Körperkraft>11;SF Linkhand' );
$sf_data['Schildkampf II']           = array( 'gruppe' => 'kampf', 'rarity' => 3, 'cost' => 200, 'req' => 'Körperkraft>14;SF Schildkampf I' );
$sf_data['Schildspalter']            = array( 'gruppe' => 'kampf', 'rarity' => 3, 'cost' => 100, 'req' => 'Körperkraft>14;SF Niederwerfen' );
$sf_data['Schnellziehen']            = array( 'gruppe' => 'kampf', 'rarity' => 4, 'cost' => 200, 'req' => 'Gewandtheit>11;Fingerfertigkeit>9' );
$sf_data['Spießgespann']             = array( 'gruppe' => 'kampf', 'rarity' => 2, 'cost' => 200, 'req' => 'Speere>9;SF Sturmangriff' );
$sf_data['Sturmangriff']             = array( 'gruppe' => 'kampf', 'rarity' => 3, 'cost' => 100, 'req' => 'Mut>11;SF Wuchtschlag' );
$sf_data['Tod von Links']            = array( 'gruppe' => 'kampf', 'rarity' => 3, 'cost' => 100, 'req' => 'SF Parierwaffen II' );
$sf_data['Todesstoß']                = array( 'gruppe' => 'kampf', 'rarity' => 3, 'cost' => 200, 'req' => 'Mut>14;SF Gezielter Stich' );
$sf_data['Umreißen']                 = array( 'gruppe' => 'kampf', 'rarity' => 3, 'cost' => 100, 'req' => 'Körperkraft>11;SF Finte' );
$sf_data['Waffe zerbrechen']         = array( 'gruppe' => 'kampf', 'rarity' => 3, 'cost' => 200, 'req' => 'Körperkraft>11;Parade Basiswert>8;SF Binden' );
$sf_data['Waffenmeister']            = array( 'gruppe' => 'kampf', 'rarity' => 1-2, 'cost' => 400, 'req' => 'Talentwert 18, 2500 AP in Kampf SFs, passende eigenschaften' );
$sf_data['Waffenmeister (Schild)']   = array( 'gruppe' => 'kampf', 'rarity' => 2, 'cost' => 400, 'req' => 'Körperkraft>15;Gewandtheit>14;SF Schildkampf II;SF Beidhändiger Kampf I;SF Parierwaffen I|SF Binden' );
$sf_data['Waffenspezialisierung']    = array( 'gruppe' => 'kampf', 'rarity' => 2-4, 'cost' => 20-160, 'req' => 'Talentwert 7/14/21/28' );
$sf_data['Windmühle']                = array( 'gruppe' => 'kampf', 'rarity' => 2, 'cost' => 200, 'req' => 'SF Wuchtschlag;SF Gegenhalten' );
$sf_data['Wuchtschlag']              = array( 'gruppe' => 'kampf', 'rarity' => 7, 'cost' => 200, 'req' => 'Körperkraft>11' );

$sf_data['Kulturkunde']              = array( 'gruppe' => 'allgemein', 'rarity' => 7, 'cost' => 150, 'req' => 'Klugheit>9;Intuition>9;Sprache>4' );

?>